Refactor diffeq
probabilistic-numerics/probnum pull request #179
Opened 2020-08-26 10:15 UTC by pnkraemer

steprule is now an argument for solve(), not an attribute of the solver. This is the first step of the refactoring, but independent enough that it can be merged independently.

2020-08-26 11:45 UTC, nathanaelbosch requested changes

2020-08-26 11:45 UTC, nathanaelbosch commented on src/probnum/diffeq/odefiltsmooth/ivpfiltsmooth.py
>          steprule : stepsize rule
This line can be removed from the docstring

2020-08-26 11:45 UTC, nathanaelbosch commented on src/probnum/diffeq/odefiltsmooth/ivpfiltsmooth.py
>          to Proposition 4 in Tronarp et al.
`steprule` should be added to the docstring

2020-08-26 13:48 UTC, nathanaelbosch approved these changes

2020-08-26 14:57 UTC, merged

2020-08-26 18:08 UTC, JonathanWenger commented
@pnkraemer Did you use admin privileges to merge this even though `black` is failing? Currently `black` is failing on master.

2020-08-27 06:25 UTC, pnkraemer commented
not that I know of, but in any case black did not complain about this PR.

2020-08-27 06:39 UTC, nathanaelbosch commented
This could again be due to a new Black release. I'll fix it by pinning the version.