Documentation fixes in diffeq
probabilistic-numerics/probnum pull request #224
Opened 2020-10-19 13:28 UTC by pnkraemer

Nina and I found out that there are some typos in the documentation. This is fixed now. The changes are tiny.

2020-10-19 14:12 UTC, nathanaelbosch requested changes
Looks good, but any idea why pylint is failing? We should fix that before merging.

2020-10-20 07:54 UTC, pnkraemer commented
Lots of complaints in the random_variable module. Not sure why...

2020-10-22 19:44 UTC, nathanaelbosch approved these changes

2020-11-04 07:05 UTC, pnkraemer commented
Oops, looks like someone forgot about this one... I will merge it now. Thanks for your patience! :)

2020-11-04 07:05 UTC, merged