Initialization routines for ODE filters
probabilistic-numerics/probnum pull request #490
Opened 2021-07-17 13:05 UTC by pnkraemer

# In a Nutshell
This PR introduces an interface for initialization routines in ODE filters.

# Detailed Description
See above. This PR also cleans up the tests for initialization routines and updates some docs.

2021-07-17 14:19 UTC, pnkraemer commented on src/probnum/diffeq/_probsolve_ivp.py
> +        initialization_routine=rk_init,
In my opinion, passing the initialisation routine with these objects is so easy that the alternative constructors are rather in the way than helpful.

2021-07-17 14:21 UTC, pnkraemer commented on src/probnum/diffeq/odefiltsmooth/initialize/_initialize.py
> +        return self._requires_jax
I see the potential point of criticism that these properties are not super useful.
I opted for introducing them anyway for communication reasons: in order to document more clearly in which sense the routines may not be interchangeable (`is_exact`), and in which case they have unusual requirements (`requires_jax`).

2021-07-17 14:22 UTC, pnkraemer commented on src/probnum/diffeq/odefiltsmooth/initialize/_taylor_mode.py
> +    ) -> randvars.RandomVariable:
please let me know if the changed naming (and some reordering) makes it easier to understand what this code does :)

2021-07-17 14:25 UTC, pnkraemer commented on src/probnum/diffeq/odefiltsmooth/initialize/_initialize.py
> +class InitializationRoutine(abc.ABC):
I opted for making this a class for multiple reasons:
1) the routine should only have the interface (ivp, prior) -> rv. Runge-Kutta initialisation has some additional parameters, which should not be part of the call signature IMO
2) For different ODEs, these routines might offer multiple options
3) it is easier to document some properties, e.g. whether the initialization is exact or not
4) it is a MUCH easier type in the constructor of GaussianIVPFilter

2021-07-19 10:09 UTC, nathanaelbosch requested changes
The PR looks good, I just found a single typo and otherwise I have nothing to complain. Thanks a lot!

2021-07-19 10:21 UTC, nathanaelbosch approved these changes

2021-07-19 10:23 UTC, merged