Fix a bunch of pylint errors in filtsmooth
probabilistic-numerics/probnum pull request #611
Opened 2022-01-12 10:38 UTC by pnkraemer

# In a Nutshell
Fix a bunch of pylint errors in filtsmooth.

# Detailed Description
Tbd

2022-01-12 10:41 UTC, pnkraemer commented on src/probnum/filtsmooth/particle/_particle_filter.py
> +    def _importance_rv_generator(
I made these two functions private because they are only used internally anyway.

2022-01-19 13:44 UTC, marvinpfoertner requested changes
Please add the colons after argument names without a type annotation again and ignore the resulting pylint error. See the Slack thread in the software channel for more information on this

2022-01-19 14:23 UTC, marvinpfoertner commented on src/probnum/filtsmooth/_timeseriesposterior.py
>          t :
```suggestion
        t
```

2022-01-19 14:23 UTC, marvinpfoertner commented on src/probnum/filtsmooth/_timeseriesposterior.py
>          size :
```suggestion
        size
```

2022-01-19 14:23 UTC, marvinpfoertner commented on src/probnum/filtsmooth/_timeseriesposterior.py
>          base_measure_realizations :
```suggestion
        base_measure_realizations
```

2022-01-19 14:23 UTC, marvinpfoertner commented on src/probnum/filtsmooth/_timeseriesposterior.py
>          t :
```suggestion
        t
```

2022-01-19 14:28 UTC, marvinpfoertner commented on src/probnum/filtsmooth/particle/_particle_filter.py
>      rng :
```suggestion
    rng
```

2022-01-19 14:28 UTC, marvinpfoertner commented on src/probnum/filtsmooth/particle/_particle_filter.py
>      with_resampling :
```suggestion
    with_resampling
```

2022-01-19 14:28 UTC, marvinpfoertner commented on src/probnum/filtsmooth/particle/_particle_filter.py
>      resampling_percentage_threshold :
```suggestion
    resampling_percentage_threshold
```

2022-01-19 14:29 UTC, marvinpfoertner commented on src/probnum/filtsmooth/particle/_particle_filter.py
>          regression_problem :
```suggestion
        regression_problem
```

2022-01-19 19:09 UTC, marvinpfoertner approved these changes

2022-01-20 12:14 UTC, merged