Refactor LinearOperator for method overriding
probabilistic-numerics/probnum pull request #735
Opened 2022-11-07 09:12 UTC by timweiland

# In a Nutshell
_matmul, _apply, _transpose etc. can now be implemented by overriding the corresponding methods in a subclass instead of passing the implementations in the constructor. The previous approach is still possible via the new LambdaLinearOperator.

# Detailed Description
* Refactor LinearOperator such that method implementations are provided via subclass overrides
* Introduce LambdaLinearOperator subclass which provides support for the old approach of passing method implementations via the constructor
* Replace all previous uses of LinearOperator with LambdaLinearOperator to maintain compatibility

2022-11-07 14:12 UTC, marvinpfoertner requested changes
Thanks for taking care of this! 🙏🏻 

Some general points:
- Instead of just saying "You may implement this method in a subclass.", we should probably state that overriding the default implementation only makes sense if we know a more efficient implementation (in terms of memory or computation time) than the fallback.
- Can you get rid of the double underscores in the cache variables? We don't really need those anymore

2022-11-07 14:12 UTC, marvinpfoertner commented on src/probnum/linops/_linear_operator.py
```suggestion
        try:
            self._transpose_cache = self._transpose()
        except NotImplementedError:
```

2022-11-07 14:12 UTC, marvinpfoertner commented on src/probnum/linops/_linear_operator.py
> +        return self._transpose_fallback()
```suggestion
            self._transpose_cache = TransposeLinearOperator(self)

        return self._transpose_cache
```

2022-11-07 14:12 UTC, marvinpfoertner commented on src/probnum/linops/_linear_operator.py
>          return TransposedLinearOperator(self)
I added the transpose fallback in the suggestions for the `_transpose` method, so we can simply remove this

2022-11-07 14:12 UTC, marvinpfoertner commented on src/probnum/linops/_linear_operator.py
> +        self._transpose_attr = transpose
```suggestion
        self._transpose_attr = (
            transpose
            if transpose is not None
            else TransposeLinearOperator(self, matmul=rmatmul)
        )
```

2022-11-07 14:12 UTC, marvinpfoertner commented on src/probnum/linops/_linear_operator.py
> +        raise NotImplementedError()
```suggestion
    def _call_if_implemented(self, method: Optional[callable]) -> callable:
        if method is not None:
            return method
        raise NotImplementedError()
```

2022-11-08 07:20 UTC, JonathanWenger commented
Great job on your first PR @timweiland. To fix the fromatting and isort issues, once you've installed tox you can run
```bash
tox -e format
```
To automatically keep code formatted you can also install the formatting libraries directly via
```
cd probnum
pip install -r formatting-requirements
```
You can then run `black` and `isort` on save in VSCode for example. To avoid comitting files which are incorrectly formatted in the future you can also alternatively install the provided precommit hooks to check for correct formatting prior to comitting (see https://probnum.readthedocs.io/en/latest/development/pull_request.html#pre-commit-hooks)

2022-11-08 10:20 UTC, timweiland commented
Thanks @JonathanWenger! I've fixed all of the problems now except for one which I'm unsure about:
Pylint complains that in this code, self.T is not callable (E1102): `y = (self.T)(x, axis=-1)`
But clearly, self.T returns a LinearOperator which is callable: `def T(self) -> "LinearOperator":`
Do you know how to fix this? [It seems that it might have something to do with the @property decorator.](https://stackoverflow.com/questions/53598374/pylint-giving-not-callable-error-for-object-property-that-is-callable)

2022-11-08 11:29 UTC, timweiland commented
> Thanks @JonathanWenger! I've fixed all of the problems now except for one which I'm unsure about: Pylint complains that in this code, self.T is not callable (E1102): `y = (self.T)(x, axis=-1)` But clearly, self.T returns a LinearOperator which is callable: `def T(self) -> "LinearOperator":` Do you know how to fix this? [It seems that it might have something to do with the @property decorator.](https://stackoverflow.com/questions/53598374/pylint-giving-not-callable-error-for-object-property-that-is-callable)

I talked to @marvinpfoertner about this and we agreed to simply make pylint ignore this line.

2022-11-08 15:27 UTC, marvinpfoertner approved these changes
Thanks again for doing this! :) Congrats on you first ProbNum PR! 🎉

2022-11-08 19:24 UTC, merged